version: "3.7"
services:
  db_v1:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: migrationapp
      MYSQL_DATABASE: migrationapp
      MYSQL_USER: migrationapp
      MYSQL_PASSWORD: migrationapp
    ports:
      - 3310:3306

  db_v2:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: migrationapp
      MYSQL_DATABASE: migrationapp
      MYSQL_USER: migrationapp
      MYSQL_PASSWORD: migrationapp
    ports:
      - 3311:3306
    
  db_mongo:
    image: mongo:4.2.6
    ports:
        - 8082:8081
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: migrationapp